<a href="https://colab.research.google.com/github/xalejandrow/machine-learning-prework/blob/main/02-numpy/02.1-Intro-to-Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/numpy_logo.png?raw=1" alt="logo" width="400"/>

## Introduction to numpy

NumPy stands for 'Numerical Python'. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrixes, along with many high-level mathematical functions that operate on them. It contains among other things:

→ a powerful N-dimensional array object.

→ sophisticated (broadcasting) functions.

→ tools for integrating C/C++ and Fortran code.

→ useful linear algebra, Fourier transform, and random number capabilities.

## Installing NumPy
When you want to work with numpy locally, you should run the following commands:

You can install NumPy with:\
`pip install numpy`\
or\
`conda install numpy`

In our case, 4Geeks have prepared all the environment in order that you can work comfortably.

## Why should we use NumPy?

Numpy is a library that performs numerical calculations in python. We will use it mainly because it allows us to create, modify matrixes, and do operations on them with ease.

NumPy is like Pandas, Matplotlib or Scikit-Learn. It is one of the packages that you cannot miss when you are studying Machine Learning. Mainly because this library provides a matrix data structure that has some benefits over regular Python lists. Some of these benefits are: being more compact, quicker access to reading and writing articles, more convenient and efficient.

For example, we will see later in the bootcamp that working with images is dealing with three-dimensional matrixes as large as 3840 x 2160, which means we will have 3×3840×2160 = 24883200 entries!!! 😱😱😱.

Working with matrixes of that magnitude is practically impossible to carry out with lists and dictionaries if one wants to have an efficient and fast programming.

#### Exercise: Import the numpy package under the name `np` (★☆☆)

`numpy` is commonly imported as `np` so we highly recommend to put this alias.

In [2]:
import numpy as np

## What is an array and why it is important for Machine Learning?

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one index or key.


![alt text](assets/1D.png "1D")

An array is known as the central data structure of the Numpy library; it can also be of several dimensions. For example, neural networks sometimes deal with 4D arrays.

Later on, we are also going to use another kind of arrays called: Tensors.

![alt text](./assets/3D.png "3D")

#### Exercise: Print the version and configuration of numpy (★☆☆)

You can print the version of any package of Python using `name_of_package.__version__`

In [3]:
import numpy as np
print(np.__version__)

1.21.6


#### Exercise: Create a null vector of size 10 (★☆☆)

A `null vector` is an array of zeros (`0`), also called `initialization vector`.

>Check de function `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [ ]:
np.zeros(0)

array([], dtype=float64)

#### Exercise: Create a vector of ones with size 10 (★☆☆)

>Check de function `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise: Create an 1D array with a specific start value, end value, and number of values (★☆☆)

>Check the function `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [ ]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

#### Run: Create a vector (1D array) with random integers from 10 to 49 and dimension 1x35 (★☆☆)

When `dimension` is expressed `1x35` it means: One dimension array with 35 items (length=35).

>Check the function `np.random` which allows you to create random arrays (https://numpy.org/doc/1.16/reference/routines.random.html)

In [1]:
import numpy as np

## 10 random numbers between (0, 1)
print(np.random.random(10)) 

[5.62009066e-01 4.49590805e-01 5.64433921e-01 3.03645859e-01
 7.19157019e-04 5.70159834e-01 5.14108840e-01 1.58850621e-02
 7.96479999e-01 7.99836746e-01]


In [2]:
## Two ways to create numbers with normal distribution
print(np.random.rand(10)) # 10 random values with distribution N(0,1)
print(np.random.normal(loc = 0, scale = 1, size = 10)) # 10 random values with distribution N(0,1)

[0.77830427 0.94514293 0.7342958  0.42883523 0.98853945 0.02722579
 0.80583382 0.51790276 0.59669088 0.40926364]
[ 1.45267776 -0.26916395 -2.28707713  0.2328964   0.27744032 -0.16752704
  1.06298252  0.73350853 -0.03262398 -0.2693362 ]


In [3]:
## Did you notice the difference between both functions? 
print(np.random.normal(loc = -5, scale = 33, size = 10)) # 10 random values with distribution N(-5,33)

[-32.94609937  -4.63470313   0.66209037 -10.65556335  -2.68112895
  44.93813031   3.9337291  -45.88041615   2.52169947  18.69168172]


In [4]:
## 10 random values with uniform distribution. That means, all values have the same probability
print(np.random.uniform(-30,100,10)) # All values are between -30 and 100.

[  2.44951065  41.7505646   89.59848015  41.63033448 -29.23118296
  11.36492557  91.14472885  38.97084225  96.41011635  42.6274657 ]


In [5]:
# 10 integers values between 0 and 100.
print(np.random.randint(0, 100, 10))

[38 90 29 91 28 86 26 21 77 89]


In [6]:
# 10 random values with Chi distribution with 5 degrees of freedom
print(np.random.chisquare(5,10))

[ 1.68865882  7.78861428  3.03398682 10.97681252  7.92340738  2.48789565
  4.10027396  1.15674039  6.31600058  3.58762651]


The above examples are the most common distribution and random values you will learn throughout the bootcamp. Now, let's deal with those arrays.

#### Exercise: Reverse one of the last vector we created before (first element becomes last) (★☆☆)
Try with `[::-1]`

In [7]:
vect = np.random.randint(0,100,10)
print(vect)
print(vect[::-1])

[81 80 98 72 61 45 66  0 75 77]
[77 75  0 66 45 61 72 98 80 81]


#### Exercise: Create a 5x5 identity matrix (★☆☆)

>Check the function `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Exercise: Find indexes of non-zero elements from [1,2,0,0,4,0] (★☆☆)

>Check the function `where`(https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [9]:
v = np.array([1,2,0,0,4,0])
np.where(v == 0)[0]

array([2, 3, 5])

#### Exercise: Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

>Check the function `min` (https://numpy.org/devdocs/reference/generated/numpy.where.html) and `max` (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [20]:
matrand =  np.random.random((10, 10))
print(matrand)
print(np.amin(matrand))
print(np.amax(matrand))

[[0.4249188  0.228489   0.07843951 0.06734406 0.86387058 0.26332227
  0.62648448 0.67559359 0.96774244 0.55070177]
 [0.47932947 0.5664927  0.39677141 0.54809955 0.48117641 0.14352175
  0.95741839 0.11704364 0.02375384 0.61847743]
 [0.98740324 0.46289302 0.68517317 0.34960241 0.74194612 0.44989942
  0.87280851 0.50921882 0.66283247 0.57094956]
 [0.81444051 0.87479351 0.08369429 0.15994493 0.14702826 0.07207413
  0.13900882 0.12484153 0.64229194 0.39749459]
 [0.06617836 0.77821732 0.91183075 0.54090927 0.89794185 0.39849159
  0.13937086 0.69759824 0.96805694 0.93027733]
 [0.56727899 0.18011939 0.94149505 0.9060115  0.00318799 0.74272928
  0.89891403 0.83867299 0.18634977 0.99884793]
 [0.66573687 0.38273435 0.31213511 0.79621064 0.3507202  0.92587014
  0.18582536 0.65200827 0.47972965 0.06271528]
 [0.02599839 0.18922499 0.42578427 0.39292592 0.2541597  0.91158015
  0.84027199 0.22305269 0.80626435 0.49985716]
 [0.91185819 0.99057657 0.77840219 0.50321441 0.16831389 0.41934941
  0.17896081

#### Exercise: Create a random vector of size 30 and find the mean value (★☆☆)

1.   Elemento de la lista
2.   Elemento de la lista



In [29]:
#matrand2 =  np.round(np.random.random(30)*100)
matrand2 =  np.random.random(30)*100
print(matrand2)
print(np.mean(matrand2))

[ 0.93085522  6.65248273 26.51131308 72.6328609   9.74234092 35.68804077
 87.73737587 25.04346389  6.65545272 75.16954077 69.8438638  45.36383557
 98.4827296  72.24555927 82.93044393 11.15817996 46.80031922 96.22856899
 87.66180081 31.54545137 50.19171884 90.00013699 70.45583548 11.02576468
 26.73940822 84.19969819 10.15996742 81.05636382 16.62773056 76.45050989]
50.19772044886842


#### Exercise: Define a function with your date of birth (yyyy/mm/dd) as imput, that returns a random array with the following dimensions: (★★☆)

$$yyyy-1900 \times |mm - dd|$$

In [15]:
def dateMatrix(mydate):
  data = mydate.split("/")
  f = int(data[0]) - 1900
  c = abs(int(data[1]) - int(data[2]))
  result = np.random.random((f,c))
  return result
arr = dateMatrix("2000/01/05")
print(arr)



[[2.93282809e-01 3.18881201e-01 7.09287750e-01 2.53125724e-01]
 [5.02665669e-01 5.06116122e-01 1.68469991e-01 7.52332576e-01]
 [7.68139069e-01 4.98750799e-01 4.17039156e-01 1.80266999e-01]
 [6.03740807e-01 6.49719561e-01 2.34220997e-01 8.56577222e-01]
 [4.16242183e-01 6.36346469e-01 9.07319712e-01 2.98362823e-01]
 [2.77025568e-01 6.81516786e-01 6.30408765e-01 9.72623437e-01]
 [6.04710773e-01 9.92483270e-02 1.68723263e-01 6.04840704e-01]
 [7.09794186e-02 4.64512414e-01 8.49228469e-01 9.78185024e-01]
 [5.84285977e-01 6.89845296e-01 3.80602473e-01 6.61650659e-01]
 [1.76050714e-01 9.06108499e-01 9.50184308e-01 7.37121887e-01]
 [6.92357553e-01 2.96316487e-01 1.59430295e-01 8.21658134e-01]
 [6.84672564e-01 3.77528333e-01 4.42468757e-01 9.11872935e-01]
 [4.57173281e-01 4.15785256e-04 7.04878306e-01 2.02767804e-01]
 [8.66385223e-02 1.10863986e-01 8.85295210e-01 8.18556085e-01]
 [7.74015878e-01 1.85135313e-01 6.60301606e-01 9.03320531e-01]
 [1.50422612e-01 8.97049889e-01 2.33894104e-01 6.165161

## What is the difference between Python List and a Numpy Array?

- Python list can contain elements with different data types, while Numpy Array‘s elements are always homogeneous (same data types).

- Numpy arrays are faster and more compact than Python lists.

## Why Numpy Arrays are faster than Lists?

- Numpy Arrays use fixed memory to store data and less memory than Python lists.

- Contiguous memory allocation in Numpy Arrays.

#### Exercise: Convert the list `my_list = [1, 2, 3]` to numpy array (★☆☆)

In [19]:
my_list = [ 1, 2, 3 ]
print(my_list)
print(type(my_list))
my_array = np.asarray(my_list)
print(type(my_array))
print(my_array)

[1, 2, 3]
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]


#### Exercise: Convert the tuple `my_list = (1, 2, 3)` to numpy array (★☆☆)

In [18]:
my_list = (1, 2, 3)
print(my_list)
print(type(my_list))
my_array = np.asarray(my_list)
print(type(my_array))
print(my_array)

(1, 2, 3)
<class 'tuple'>
<class 'numpy.ndarray'>
[1 2 3]


#### Exercise: Convert the list of tuples `my_list = [(1,2,3), (4,5)]` to numpy array (★☆☆)

In [28]:
my_list = [(1,2,3), (4,5)]
print(my_list)
print(type(my_list))
my_array = np.asanyarray(my_list,dtype='object')
print(my_array)
print(type(my_array))

[(1, 2, 3), (4, 5)]
<class 'list'>
[(1, 2, 3) (4, 5)]
<class 'numpy.ndarray'>


#### Exercise: Resize a random array of dimensions 5x12 into 12x5 (★☆☆)

>Check `reshape` from `numpy` (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

#### Exercise: Create a function that normalize a 5x5 random matrix (★☆☆)

>Remember from probability (https://en.wikipedia.org/wiki/Normalization_(statistics)) that :
$$ x_{norm} = \frac{x - \bar{x}}{\sigma}$$


## Stacking numpy arrays

Stacking is used to join a sequence of same dimension arrays along a new axis.

`numpy.stack(arrays,axis)` : It returns a stacked array of the input arrays which has one more dimension than the input arrays.

### You have two ways to do it:


![alt text](./assets/stack.jpeg "stack")


### or


![alt text](./assets/stack2.jpeg "stack")




#### Exercise: Generate two random arrays with integers and apply the stacking using `stack` (★★☆)

#### Exercise: Generate two random arrays with integers and apply the stacking using `hstack` and `vstack` (★★☆)

## Basic maths in numpy

You can make typical math operations like:

- Addition,Subtraction,Multiplication and Division between two arrays using numpy.
- Operation on arrays using sum() & cumsum() function.
- Minimum and Maximum value from an array.
- Exponent/Power , Square Root and Cube Root functions.

or even apply common trigonometric functions:

- `numpy.sin()`:  Sine (x) Function
- `numpy.cos()`: Cosine(x) Function
- `numpy.tan()`: Tangent(x) Function
- `numpy.sinh()`: Hyperbolic Sine (x) Function
- `numpy.cosh()`: Hyperbolic Cosine(x) Function
- `numpy.tanh()`: Hyperbolic Tangent(x) Function
- `numpy.arcsin()`: Inverse Sine(x) Function
- `numpy.arccos()`: Inverse Cosine(x) Function
- `numpy.arctan()`: Inverse Tangent(X) Function
- `numpy.pi`: Pi value π
- `numpy.hypot(w,h)`: For calculating Hypotenuse $c = \sqrt{(w^2 + h^2)}$
- `numpy.rad2deg()`: Radians to degrees
- `numpy.deg2rad()`: Degrees to radians

#### Exercise: Generate two random 8 - dimensional vectors and apply the most common operation between vectors:  addition, substraction, multiplication, division(★☆☆)

>Check the math functions here: https://numpy.org/doc/stable/reference/routines.math.html

#### Exercise: Generate two random matrices with dimensions between 5 and 10. For example, try 5x7 vs 8x9. Were you able to do the matrix multiplication? why? (★★☆) 

#### Exercise: Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array) Were you able to do the matrix multiplication? (★★☆) 

$$ a = \left(\begin{matrix}
0 & 1 & 2\\ 
3 & 4 & 5\\ 
6 & 7 & 8
\end{matrix}\right)$$

$$ b = \left(\begin{matrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{matrix}\right)$$




#### Exercise: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★★☆)

## Data types

Do you think the following preposition is true?

`8==8`

Surely you will definetely say yes, which is true mathematically, but computationally it is not always the same, at least in terms of memory. For example, run the following cell:

In [ ]:
import sys

# int64
x = np.array(123)
print("int64: " + str(sys.getsizeof(x)))

# int8
x = np.array(123,dtype=np.int8)
print("int8: " + str(sys.getsizeof(x)))

# float32
x = np.array(123,dtype=np.float32)
print("float32: " + str(sys.getsizeof(x)))

#### It turns out that there are many computational representation of the same number and you can create arrays with different Data Types (dtypes) depending on what you need:

- Boolean : `np.bool_`
- Char : `np.byte`
- Short : `np.short`
- Integer : `np.short`
- Long : `np.int_`
- Float : `np.single`&np.float32`
- Double :`np.double`&`np.float64`
- `np.int8`: integer (-128 to 127)
- `np.int16`:integer( -32768 to 32767)
- `np.int32`: integer(-2147483648 to 2147483647)
- `np.int64`:integer( -9223372036854775808 to 9223372036854775807)


Sometimes, you will need to load, create or export arrays from different data types.


## Harder exercises

The next exercises are related with real situations you could face while you are working in data science and machine learning. Also, we will be frequently talking about matrices and bidimensional arrays.

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

#### Exercise: How to get the dates of yesterday, today and tomorrow? (★★☆)

>Check `np.datetime64`, `np.timedelta64` in numpy (https://numpy.org/doc/stable/reference/arrays.datetime.html)

#### Exercise: How to get all the dates corresponding to the month of December 2022? (★★☆)
Combine `arange`with `datetime`


#### Exercise: Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)

#### Exercise: Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### Exercise: Consider a generator function that generates 10 integers and use it to build an array (★★☆)

#### Exercise: Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### Exercise: Create a random vector of size 10 and sort it (★★☆)

#### Exercise: Consider two random arrays A and B, check if they are equal (★★☆)

#### Exercise: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★★)
>Suggestion: check how to calculate the "square of a matrix"

#### Exercise: Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### Exercise: How to print all the values of an array? (★★☆)

#### Exercise: How to convert a float (32 bits) array into an integer (32 bits) in place?
>Check: https://stackoverflow.com/a/4396247/5989906

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

#### Exercise: How to sort an array by the nth column? (★★☆)

#### Exercise: Find the position of the minimum of a 2D matrix (★★☆)

#### Exercise: Read an image using openCV, check its dimensions, normalize the numbers and show the image (★★★)

>Check: https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

#### Exercise: Considering a four dimensions array, how to get the sum over the last two axis at once? (★★★)

#### Exercise: How to get the diagonal of a dot product? (★★★)

#### Exercise: Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### Exercise: How to swap two rows of an array? (★★★)

#### Exercise: Read an image using openCV and tranpose it. What did you get exactly? Was the image rotated? Moved? Reflected with respect to an axis? (★★★)

#### Exercise: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### Exercise: How to find the most frequent value in an array? (★★★)

#### Exercise: How to get the n largest values of an array (★★★)

#### Exercise: Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### Exercise: Given a two dimensional array, how to extract unique rows? (★★★)

#### Exercise: Can you have an array of strings? Can you mix different data types in the same array? Can you operate (add, sub, mult) arrays with different data types? (★★★)